### PR TITLE
Add Summer15_50nsV4_DATA_UncertaintySources_AK4PFchs.txt file

### PR DESCRIPTION
**Pull request by mmarionncern**
Needed for the propagation of the JEC uncertainties to the MET

### CODE REVIEW

**Comment by mmarionncern** [comment]
THe V5 has been released right after the PR. As it is not merged yet, the uncertainties have been updated

**Comment by gpetruc** [comment]
Can we  integrate this, which is otherwise blocking https://github.com/cms-sw/cmssw/pull/10443 ?

**Comment by davidlange6** [comment]
@degano - lets integrate this (txt files replacing condDB in cms I guess..)

**Comment by ghost** [comment]
@mmarionncern @gpetruc @davidlange6 
Done for 7[4,5,6]X here:
https://github.com/cms-sw/cmsdist/pull/1783
https://github.com/cms-sw/cmsdist/pull/1782
https://github.com/cms-sw/cmsdist/pull/1781

**Pull request merged**
